"""
Configuration Manager for ClassSync Visual
Handles loading/saving user preferences and default settings
"""

import json
import os
from pathlib import Path
from typing import Dict, Any

class ConfigManager:
    """Manages application configuration"""
    
    def __init__(self):
        self.project_root = Path(__file__).parent.parent
        self.config_dir = self.project_root / "config"
        self.default_config_path = self.config_dir / "default_config.json"
        self.user_config_path = self.config_dir / "user_config.json"
        
        # Ensure config directory exists
        self.config_dir.mkdir(exist_ok=True)
        
        self.config = self._load_config()
    
    def _get_default_config(self) -> Dict[str, Any]:
        """Get default configuration"""
        return {
            "time_slots": {
                "start": "08:00",
                "end": "17:00",
                "slot_minutes": 90
            },
            "styling": {
                "header_color": "FF4472C4",
                "day_color": "FFD9E2F3",
                "room_color": "FFF2F2F2",
                "font_name": "Calibri",
                "font_size": 10,
                "header_font_size": 12,
                "auto_adjust_columns": True,
                "border_style": "thin"
            },
            "export_options": {
                "include_empty_days": False,
                "merge_day_cells": True,
                "show_instructor": True,
                "show_program": True,
                "compact_mode": False
            },
            "app_settings": {
                "remember_last_folder": True,
                "auto_open_output": True,
                "show_analytics": True,
                "check_conflicts": True
            },
            "colors": {
                "Mathematics": "FFE74C3C",
                "Physics": "FF3498DB",
                "Chemistry": "FF2ECC71",
                "Biology": "FF9B59B6",
                "Computer Science": "FF1ABC9C",
                "English": "FFF39C12",
                "History": "FF34495E"
            },
            "watermark": {
                "text": "Generated by ClassSync Visual",
                "show": True,
                "position": "bottom-right"
            }
        }
    
    def _load_config(self) -> Dict[str, Any]:
        """Load configuration from files"""
        # Start with default config
        config = self._get_default_config()
        
        # Ensure config directory exists
        self.config_dir.mkdir(exist_ok=True)
        
        # Save default config if it doesn't exist
        if not self.default_config_path.exists():
            self._save_config_file(self.default_config_path, config)
        
        # Load user config if it exists
        if self.user_config_path.exists():
            try:
                with open(self.user_config_path, 'r', encoding='utf-8') as f:
                    user_config = json.load(f)
                    self._merge_configs(config, user_config)
            except Exception as e:
                print(f"Warning: Could not load user config - {e}")
                print("Using default configuration...")
        
        return config
    
    def _merge_configs(self, default: Dict, user: Dict):
        """Recursively merge user config into default config"""
        for key, value in user.items():
            if key in default and isinstance(default[key], dict) and isinstance(value, dict):
                self._merge_configs(default[key], value)
            else:
                default[key] = value
    
    def _save_config_file(self, filepath: Path, config: Dict[str, Any]):
        """Save configuration to file"""
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                json.dump(config, f, indent=2, ensure_ascii=False)
        except Exception as e:
            print(f"Error saving config to {filepath}: {e}")
    
    def get(self, key_path: str, default=None):
        """Get configuration value using dot notation (e.g., 'time_slots.start')"""
        if not key_path:
            return default
            
        keys = key_path.split('.')
        value = self.config
        
        try:
            for key in keys:
                if isinstance(value, dict) and key in value:
                    value = value[key]
                else:
                    return default
            return value
        except (KeyError, TypeError, AttributeError):
            return default
    
    def set(self, key_path: str, value):
        """Set configuration value using dot notation"""
        keys = key_path.split('.')
        config_section = self.config
        
        # Navigate to the parent section
        for key in keys[:-1]:
            if key not in config_section:
                config_section[key] = {}
            config_section = config_section[key]
        
        # Set the value
        config_section[keys[-1]] = value
    
    def save_user_config(self):
        """Save current configuration as user preferences"""
        self._save_config_file(self.user_config_path, self.config)
    
    def reset_to_defaults(self):
        """Reset configuration to defaults"""
        self.config = self._get_default_config()
        # Remove user config file
        if self.user_config_path.exists():
            self.user_config_path.unlink()
    
    def get_time_slots(self):
        """Generate time slots based on configuration"""
        from datetime import datetime, timedelta
        
        start_time = datetime.strptime(self.get('time_slots.start'), "%H:%M")
        end_time = datetime.strptime(self.get('time_slots.end'), "%H:%M")
        slot_minutes = self.get('time_slots.slot_minutes')
        
        time_slots = []
        current_time = start_time
        
        while current_time < end_time:
            slot_end = current_time + timedelta(minutes=slot_minutes)
            if slot_end > end_time:
                break
            time_slots.append(f"{current_time.strftime('%H:%M')} - {slot_end.strftime('%H:%M')}")
            current_time = slot_end
        
        return time_slots
    
    def get_color_for_course(self, course_name: str) -> str:
        """Get color for a course, generating if not exists"""
        colors = self.get('colors', {})
        
        if course_name in colors:
            return colors[course_name]
        
        # Generate color based on course name hash
        import hashlib
        hash_object = hashlib.md5(course_name.encode())
        hash_hex = hash_object.hexdigest()
        
        # Extract RGB and ensure readability
        r = max(100, min(220, int(hash_hex[0:2], 16)))
        g = max(100, min(220, int(hash_hex[2:4], 16)))
        b = max(100, min(220, int(hash_hex[4:6], 16)))
        
        color_hex = f"FF{r:02X}{g:02X}{b:02X}"
        
        # Save generated color
        colors[course_name] = color_hex
        self.set('colors', colors)
        
        return color_hex