#!/usr/bin/env python3
"""
Fix configuration issues by resetting configs
"""

import json
import os
from pathlib import Path

def fix_config():
    """Fix configuration files"""
    print("🔧 ClassSync Visual - Config Fix")
    print("=" * 40)
    
    config_dir = Path("config")
    config_dir.mkdir(exist_ok=True)
    
    # Remove user config to force regeneration
    user_config_path = config_dir / "user_config.json"
    if user_config_path.exists():
        print("🗑️ Removing old user config...")
        user_config_path.unlink()
    
    # Create/update default config with all required fields
    default_config_path = config_dir / "default_config.json"
    
    correct_config = {
        "time_slots": {
            "start": "08:00",
            "end": "17:00",
            "slot_minutes": 90
        },
        "styling": {
            "header_color": "FF4472C4",
            "day_color": "FFD9E2F3",
            "room_color": "FFF2F2F2",
            "font_name": "Calibri",
            "font_size": 10,
            "header_font_size": 12,
            "auto_adjust_columns": True,
            "border_style": "thin"
        },
        "export_options": {
            "include_empty_days": False,
            "merge_day_cells": True,
            "show_instructor": True,
            "show_program": True,
            "compact_mode": False
        },
        "app_settings": {
            "remember_last_folder": True,
            "auto_open_output": True,
            "show_analytics": True,
            "check_conflicts": True
        },
        "colors": {
            "Mathematics": "FFE74C3C",
            "Physics": "FF3498DB",
            "Chemistry": "FF2ECC71",
            "Biology": "FF9B59B6",
            "Computer Science": "FF1ABC9C",
            "Engineering": "FFF39C12",
            "English": "FF34495E",
            "History": "FFAD4A28",
            "Geography": "FF16A085",
            "Economics": "FF8E44AD",
            "Psychology": "FFE67E22",
            "Sociology": "FF27AE60"
        },
        "watermark": {
            "text": "Generated by ClassSync Visual",
            "show": True,
            "position": "bottom-right",
            "font": "Arial",
            "fontsize": 10,
            "color": "FF808080"
        }
    }
    
    print("📝 Writing corrected default config...")
    with open(default_config_path, 'w', encoding='utf-8') as f:
        json.dump(correct_config, f, indent=2, ensure_ascii=False)
    
    print("✅ Configuration fixed!")
    
    # Test the fix
    print("\n🧪 Testing fixed configuration...")
    try:
        from utils.config_manager import ConfigManager
        config_manager = ConfigManager()
        
        border_style = config_manager.get('styling.border_style')
        print(f"✅ border_style now returns: {border_style}")
        
        styling = config_manager.get('styling')
        if styling and 'border_style' in styling:
            print(f"✅ border_style found in styling section: {styling['border_style']}")
        else:
            print("❌ border_style still missing from styling section")
        
    except Exception as e:
        print(f"❌ Test failed: {e}")
    
    print("\n🎉 Config fix complete! Try running the app again.")

if __name__ == "__main__":
    fix_config()
    input("\nPress Enter to exit...")