CREATE DATABASE saad;

USE saad;

CREATE TABLE STUDENT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(500),
    DATE DATE NOT NULL,
    AGE INT NOT NULL
);

INSERT INTO STUDENT VALUES (48, 'SAAD', '10-05-2001', 23);
INSERT INTO STUDENT VALUES (55, 'ISMAIL', '12-09-2003', 33);